# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Node.js CI
on:
  push:
    branches: [ main ]
    tags:
      - v*
  pull_request:
    branches: [ main ]
env:
  IMAGE_NAME: creature-api-boilerplate
jobs:
  build:
    runs-on: ubuntu-22.04
    services:
      # Label used to access the service container
      postgres:
        ports:
          - 5432:5432
        # Docker Hub image
        image: postgres:15-alpine
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: creature_api_boilerplate
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy:
      matrix:
        node-version: [18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: yarn --frozen-lockfile
    - name: Lint Check
      run: yarn lint
    - name: Build
      run: yarn compile
    - name: Coverage Upload
      uses: codecov/codecov-action@v4
  docker-build:
    runs-on: ubuntu-22.04
    if: github.event_name == 'pull_request'
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Run build
        run: docker build . --file Dockerfile